[package]
name = "wifi-commissioning-gatt-service"
version = "0.1.2"
authors = ["Roland Erk <roland.erk@conplement.de>"]
edition = "2018"
repository = "git@github.com:ICS-DeviceManagement/wifi-commissioning-gatt-service.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluer = "0.10"
futures = "0.3"
tokio = { version = "1", features = ["io-std", "io-util", "rt-multi-thread", "process"] }
uuid = "0.8"
env_logger = "0.8"
wifiscanner = "0.5.*"
wpactrl = "0.3.*"
enclose = " 1.1.8"

[build-dependencies]

[dev-dependencies]
